<?php
class JConfig {
	public $offline = '0';
	public $offline_message = 'This site is down for maintenance.<br /> Please check back again soon.';
	public $display_offline_message = '1';
	public $offline_image = '';
	public $sitename = 'קהילה משיחית בתל אביב-יפו - Born again believers in Tel aviv Israel';
	public $editor = 'jce';
	public $captcha = '0';
	public $list_limit = '20';
	public $access = '1';
	public $debug = '0';
	public $debug_lang = '0';
	public $dbtype = 'mysqli';
	public $host = 'localhost';
	public $user = 'root';
	public $password = 'root';
	public $db = 'tomifrank_baj';
	public $dbprefix = 't2e5v_';
	public $live_site = '';
	public $secret = 'GCfoYj56rnYe57Yt';
	public $gzip = '0';
	public $error_reporting = 'default';
	public $helpurl = 'http://help.joomla.org/proxy/index.php?option=com_help&keyref=Help{major}{minor}:{keyref}';
	public $ftp_host = '127.0.0.1';
	public $ftp_port = '21';
	public $ftp_user = '';
	public $ftp_pass = '';
	public $ftp_root = '';
	public $ftp_enable = '0';
	public $offset = 'UTC';
	public $mailer = 'mail';
	public $mailfrom = 'franktomi@gmail.com';
	public $fromname = 'Joomy';
	public $sendmail = '/usr/sbin/sendmail';
	public $smtpauth = '0';
	public $smtpuser = '';
	public $smtppass = '';
	public $smtphost = 'localhost';
	public $smtpsecure = 'none';
	public $smtpport = '25';
	public $caching = '0';
	public $cache_handler = 'file';
	public $cachetime = '15';
	public $MetaDesc = 'קהילה משיחית בתל אביב-יפו - Born again believers in Tel aviv Israel
אנחנו מאמינים משיחיים. אנחנו מאמינים בספר התנ"ך והברית החדשה. יש בינינו יהודים וגם לא יהודים. אנחנו מאמינים שישוע מנצרת הוא המשיח המובטח בתנ"ך. הוא מת כדי לתת לנו סליחת חטאים וחיי נצח בגן עדן';
	public $MetaKeys = 'קהילה משיחית,קהילה משיחית בתל אביב,יהודים משיחיים,ישוע,ישוע המשיח,הברית החדשה,מאמינים משיחיים,סליחת חטאים,כפרה נצחית, church, church in tel aviv, christian church in tel aviv, christian fellowship in tel aviv,christian congregation in tel aviv,christian assembly in tel aviv,born again christians in tel aviv,messianic jews in tel aviv';
	public $MetaTitle = '1';
	public $MetaAuthor = '1';
	public $MetaVersion = '0';
	public $robots = '';
	public $sef = '1';
	public $sef_rewrite = '1';
	public $sef_suffix = '0';
	public $unicodeslugs = '1';
	public $feed_limit = '10';
	public $log_path = '/home/tomi/public_html/joomy/logs';
	public $tmp_path = '/home/tomi/public_html/joomy/tmp';
	public $lifetime = '15';
	public $session_handler = 'database';
	public $MetaRights = '';
	public $sitename_pagetitles = '2';
	public $force_ssl = '0';
	public $feed_email = 'author';
	public $cookie_domain = '';
	public $cookie_path = '';
}
